const Billing = require('../models/Billing');
const { amountOf, isPaid } = require('../models/Billing');

/**
 * What the caller owes, attributed to their account — derived from `bills` on read,
 * never stored on Account, so paying a bill can't leave a stale balance behind.
 *
 * ⚠️ Schema mismatch, deliberately surfaced rather than papered over.
 *
 * The consumer UI shows a balance per water account. The portal's bills are keyed on
 * `consumerId`, so "what does ACC-2026-0004 owe" has no answer in the data whenever
 * one consumer holds more than one account — their bills cannot be split back out
 * per meter.
 *
 * ⚠️ PARTLY OBSOLETE, AND NOT SAFE TO ACT ON YET. Bills generated by the portal's
 * current billing run do carry `connectionId` (see models/Billing.js), which is the
 * missing account reference. Wiring it up would change what the district tells a
 * household it owes, so it wants its own change, against bills from a real billing
 * run — the only bills carrying that field today are three test documents.
 *
 * ⚠️ THE AMBIGUITY IS ABOUT THE CALLER'S BILLS, NOT ABOUT THE METER. This used to
 * take an Account and bail when `account.consumerIds.length !== 1`, which asked the
 * wrong question twice over: `consumerIds` is a dangling seed-script field that
 * matches nothing in the district's database (see models/Account.js), and a *shared*
 * meter does not actually make the balance unattributable. If a consumer holds
 * exactly one account, every bill addressed to them is a bill for that account —
 * whoever else happens to be on the same meter has their own bills, and those were
 * never in this consumer's set to begin with.
 *
 * So the question is: does ONE REGISTRY CONSUMER hold one account, or several?
 * One is derivable and we report it. Several returns `outstanding: null`, because
 * the plausible alternatives are all wrong in ways that matter: attributing the
 * full balance to each account double-counts what the household owes, and
 * splitting it evenly invents a division the district never made. A consumer who
 * reads either one and pays it is going to the counter with the wrong amount.
 *
 * ⚠️ THE QUESTION IS PER REGISTRY CONSUMER, NOT PER CALLER. That distinction did
 * not exist while a caller was always exactly one `consumers` row. A Google
 * identity holding several ConsumerLinks is not: each linked account resolves
 * through its own service connection to its own registry consumer, and two
 * accounts owned by two different consumers have two separately attributable
 * balances. Bailing on "the caller holds more than one account" would report
 * null for both, which is a worse answer than the data supports — see
 * balancesByConnection below, which asks the question once per consumer.
 *
 * The real fix is an account reference on the bill, which belongs to the portal's
 * billing run. Until then callers must render null as "See total balance" rather
 * than as ₱0.00 — zero is a specific and dangerous claim here.
 *
 * @param {string} consumerId  The caller — `req.user.sub`, never a request parameter.
 * @param {number} accountCount  How many accounts the caller holds.
 * @returns {Promise<{ outstanding: number|null, paymentStatus: 'Active'|'Past Due'|'Unknown' }>}
 */
async function attributableBalance(consumerId, accountCount) {
  if (accountCount !== 1) {
    return { outstanding: null, paymentStatus: 'Unknown' };
  }

  /**
   * Status and money both go through models/Billing helpers rather than being read
   * off the document. This function used to compare `b.status !== 'paid'` against a
   * portal that writes `PAID`, so every settled bill counted as outstanding, and to
   * add `b.amount` — a field the real documents do not have — which made the total
   * `NaN` on the first bill and `₱—` on the screen.
   */
  const bills = await Billing.listForConsumer(consumerId);
  const unpaid = bills.filter((b) => !isPaid(b));

  /**
   * `Past Due` is derived from the due date here, not from the portal's `OVERDUE`
   * flag, matching what billingController tells the same consumer on the Bills
   * screen. The flag is only as fresh as the last billing run; two screens
   * disagreeing about whether a household is late is worse than either answer.
   */
  const today = Date.now();
  const totals = unpaid.map(amountOf);

  return {
    outstanding: totals.reduce((sum, amount) => sum + (amount ?? 0), 0),
    paymentStatus: unpaid.some((b) => b.dueDate && b.dueDate.getTime() < today)
      ? 'Past Due'
      : 'Active',
  };
}

/**
 * Per-connection balances for a set of service connections.
 *
 * Groups by `consumerId` first, because that is the level the ambiguity lives at.
 * A consumer owning exactly one connection in this set gets a real number; one
 * owning several gets null for each of theirs, and their neighbours in the same
 * response are unaffected.
 *
 * Concretely, for a Google identity linked to two accounts owned by two
 * different registry consumers, both balances resolve. Before this, the caller
 * "held more than one account" and both rows read "See total balance" — the app
 * telling someone with two houses that it could not say what either owed, while
 * the bills for each sat in the database under different consumer ids.
 *
 * Still NOT keyed on the bill's `connectionId`, which would settle the
 * several-accounts-one-consumer case too. That is the real fix and it is
 * deliberately not taken here: see the warning above about acting on a field
 * that only test bills carry today. It changes what the district tells a
 * household it owes and wants its own change against real billing-run data.
 *
 * @param {Array<{_id: any, consumerId: any}>} connections
 * @returns {Promise<Map<string, { outstanding: number|null, paymentStatus: string }>>}
 *          keyed by String(connection._id)
 */
async function balancesByConnection(connections) {
  const countByConsumer = new Map();
  for (const c of connections) {
    const key = String(c.consumerId);
    countByConsumer.set(key, (countByConsumer.get(key) || 0) + 1);
  }

  // One balance lookup per consumer, not per connection.
  const balanceByConsumer = new Map();
  for (const [consumerId, count] of countByConsumer) {
    balanceByConsumer.set(consumerId, await attributableBalance(consumerId, count));
  }

  return new Map(
    connections.map((c) => [
      String(c._id),
      balanceByConsumer.get(String(c.consumerId)) ?? {
        outstanding: null,
        paymentStatus: 'Unknown',
      },
    ])
  );
}

module.exports = { attributableBalance, balancesByConnection };
