import * as AuthSession from 'expo-auth-session';
import { useCallback, useState } from 'react';

import {
  GOOGLE_DISCOVERY,
  GOOGLE_SCOPES,
  googleAuthConfig,
} from '@/shared/config/google-auth-config';
import * as api from '@/shared/services/google-api-client';
import type { GoogleSession, GoogleSignInFailure } from '@/shared/types/google-auth';

/**
 * The Google browser flow, as a hook, so the landing screen and the
 * standalone /google-login route run ONE implementation.
 *
 * This was lifted out of google-login-screen.tsx the moment a second caller
 * appeared. The logic below is security-relevant in a quiet way — PKCE
 * generation, an id_token that must reach the backend untouched, a set of
 * failure kinds that decide what the user is told — and two copies of it
 * would be two places to fix when Google changes something, with the second
 * one found in production.
 *
 * Flow per attempt:
 *   1. Browser opens Google's consent page (Authorization Code + PKCE — no
 *      client secret exists anywhere in this app).
 *   2. The code comes back via the app's reverse-client-id redirect scheme;
 *      expo-auth-session exchanges it at Google's token endpoint.
 *   3. The resulting id_token goes STRAIGHT to POST /auth/google/callback,
 *      untouched. No claim of it is decoded or acted on here — the device has
 *      no way to verify a Google signature, so every claim check belongs to
 *      the backend that holds the JWKS.
 *   4. The session is handed to `onSuccess`, which is wired to auth-context's
 *      signInWithGoogle. Route guards take over from there; neither this hook
 *      nor its callers ever navigate.
 */

const authConfig = googleAuthConfig();

export interface GoogleSignInController {
  /**
   * False on web, where googleAuthConfig() returns null because
   * makeRedirectUri produces an origin Google refuses. Callers hide or
   * explain the button rather than showing one that cannot work.
   */
  configured: boolean;
  /** PKCE material is still generating; a tap now would open nothing. */
  ready: boolean;
  submitting: boolean;
  failure: GoogleSignInFailure | null;
  clearFailure: () => void;
  start: () => Promise<void>;
}

export function useGoogleSignIn(onSuccess?: (session: GoogleSession) => void): GoogleSignInController {
  // PKCE + state are generated by the hook; responseType Code is the modern
  // grant (the implicit flow Google once used here is deprecated). prompt=
  // select_account lets someone with several Google accounts pick deliberately
  // instead of silently resuming whichever one the browser remembers. The
  // hook's `response` slot is unused: results are consumed from promptAsync's
  // return value inside start(), which keeps one code path for all outcomes.
  const [request, , promptAsync] = AuthSession.useAuthRequest(
    {
      clientId: authConfig?.clientId ?? '',
      redirectUri: authConfig?.redirectUri ?? '',
      scopes: GOOGLE_SCOPES,
      responseType: AuthSession.ResponseType.Code,
      usePKCE: true,
      extraParams: { prompt: 'select_account' },
    },
    GOOGLE_DISCOVERY
  );

  const [failure, setFailure] = useState<GoogleSignInFailure | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const start = useCallback(async () => {
    if (!authConfig || !request || submitting) return;
    setFailure(null);
    setSubmitting(true);
    try {
      const result = await promptAsync();

      if (result.type === 'error') {
        console.warn('[google-auth] provider error:', result.params?.error);
        setFailure({ kind: 'provider', detail: result.params?.error });
        return;
      }

      if (result.type !== 'success') {
        // Closed browser / dismissed / locked. Expected behaviour, not an
        // error — say so plainly and let them retry.
        setFailure({ kind: 'cancelled' });
        return;
      }

      if (!result.params.code || !request.codeVerifier) {
        console.warn('[google-auth] success result missing code or verifier');
        setFailure({ kind: 'provider' });
        return;
      }

      const tokens = await AuthSession.exchangeCodeAsync(
        {
          clientId: authConfig.clientId,
          code: result.params.code,
          redirectUri: authConfig.redirectUri,
          // `code_verifier`, snake_case — NOT `codeVerifier`. TokenRequest's
          // getQueryBody() copies extraParams keys into the token request body
          // verbatim, so a camelCase key ships a body param Google ignores and
          // omits the one PKCE requires; the exchange then dies on invalid_grant
          // with nothing on screen to say why. expo-auth-session's own Google
          // provider spells it this way (src/providers/Google.ts).
          extraParams: { code_verifier: request.codeVerifier },
        },
        GOOGLE_DISCOVERY
      );

      // Opaque handoff — see the header. If Google ever returns no id_token
      // (scope regression, misconfigured client), that is fatal here: there is
      // nothing else this flow can offer the backend.
      if (!tokens.idToken) {
        console.warn('[google-auth] token exchange returned no id_token');
        setFailure({ kind: 'provider' });
        return;
      }

      const session = await api.exchangeGoogleIdToken(tokens.idToken);
      // Persistence + state entry belong to the caller (auth-context via the
      // route). When they resolve, the calling screen is unmounted by guards.
      onSuccess?.(session);
    } catch (error) {
      setFailure(error as GoogleSignInFailure);
    } finally {
      setSubmitting(false);
    }
  }, [request, promptAsync, submitting, onSuccess]);

  return {
    configured: Boolean(authConfig),
    ready: Boolean(request),
    submitting,
    failure,
    clearFailure: useCallback(() => setFailure(null), []),
    start,
  };
}

/** Copy keyed by failure kind — generic by policy. Nothing here hints at
 * whether an email exists, is allowlisted, or was rejected for which reason.
 * Shared so /login and /google-login cannot drift into telling users two
 * different stories about the same failure. */
export const GOOGLE_FAILURE_TITLES: Record<GoogleSignInFailure['kind'], string> = {
  cancelled: 'Sign-in cancelled',
  provider: "Couldn't complete sign-in",
  rejected: 'Sign-in failed',
  network: 'Cannot reach TWD',
};

export const GOOGLE_FAILURE_BODIES: Record<GoogleSignInFailure['kind'], string> = {
  cancelled: 'You closed the Google window before finishing. Tap continue to try again.',
  provider: 'Google reported a problem with the sign-in attempt. Please try again.',
  rejected: 'Your Google account could not be verified. Please try again.',
  network: 'Check your internet connection and try again.',
};
